-- 创建二维码替换记录表
CREATE TABLE RECORD_QR_CODE_REPLACE (
    -- 基类字段
    ID NUMBER(20) NOT NULL,
    CREATE_TIME TIMESTAMP,
    UPDATE_TIME TIMESTAMP,
    CREATOR NUMBER(20),
    UPDATER NUMBER(20),
    DELETED NUMBER(1) DEFAULT 0,
    
    -- 业务字段
    ORIGINAL_QR_CODE VARCHAR2(100),
    REPLACE_QR_CODE VARCHAR2(100),
    SUBMIT_DATETIME TIMESTAMP,
    SUBMIT_USER_ID NUMBER(20),
    SUBMIT_USERNAME VARCHAR2(50),
    HANDLE_DATETIME TIMESTAMP,
    HANDLE_FLAG NUMBER(1) DEFAULT 0,
    
    -- 主键约束
    CONSTRAINT PK_RECORD_QR_CODE_REPLACE PRIMARY KEY (ID)
);

-- 添加表注释
COMMENT ON TABLE RECORD_QR_CODE_REPLACE IS '二维码替换记录表';

-- 添加字段注释
COMMENT ON COLUMN RECORD_QR_CODE_REPLACE.ID IS '主键ID';
COMMENT ON COLUMN RECORD_QR_CODE_REPLACE.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN RECORD_QR_CODE_REPLACE.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN RECORD_QR_CODE_REPLACE.CREATOR IS '创建者';
COMMENT ON COLUMN RECORD_QR_CODE_REPLACE.UPDATER IS '更新者';
COMMENT ON COLUMN RECORD_QR_CODE_REPLACE.DELETED IS '删除标记(0:未删除,1:已删除)';

COMMENT ON COLUMN RECORD_QR_CODE_REPLACE.ORIGINAL_QR_CODE IS '原始二维码';
COMMENT ON COLUMN RECORD_QR_CODE_REPLACE.REPLACE_QR_CODE IS '替换二维码';
COMMENT ON COLUMN RECORD_QR_CODE_REPLACE.SUBMIT_DATETIME IS '提交时间';
COMMENT ON COLUMN RECORD_QR_CODE_REPLACE.SUBMIT_USER_ID IS '提交用户ID';
COMMENT ON COLUMN RECORD_QR_CODE_REPLACE.SUBMIT_USERNAME IS '提交用户名';
COMMENT ON COLUMN RECORD_QR_CODE_REPLACE.HANDLE_DATETIME IS '处理时间';
COMMENT ON COLUMN RECORD_QR_CODE_REPLACE.HANDLE_FLAG IS '处理状态(0:未处理,1:已处理)';

-- 创建索引
CREATE INDEX IDX_RECORD_QR_CODE_REPLACE_ORIGINAL ON RECORD_QR_CODE_REPLACE(ORIGINAL_QR_CODE);
CREATE INDEX IDX_RECORD_QR_CODE_REPLACE_REPLACE ON RECORD_QR_CODE_REPLACE(REPLACE_QR_CODE);
CREATE INDEX IDX_RECORD_QR_CODE_REPLACE_SUBMIT_TIME ON RECORD_QR_CODE_REPLACE(SUBMIT_DATETIME);
CREATE INDEX IDX_RECORD_QR_CODE_REPLACE_HANDLE_FLAG ON RECORD_QR_CODE_REPLACE(HANDLE_FLAG); 