-- 添加 alias 字段
ALTER TABLE PRODUCTION_DEPART_AND_WORKSHOP ADD ALIAS VARCHAR2(200);
COMMENT ON COLUMN PRODUCTION_DEPART_AND_WORKSHOP.ALIAS IS '别名';

-- 添加 codeRuleId 字段
ALTER TABLE PRODUCTION_DEPART_AND_WORKSHOP ADD CODE_RULE_ID NUMBER(20);
COMMENT ON COLUMN PRODUCTION_DEPART_AND_WORKSHOP.CODE_RULE_ID IS '编码规则ID'; 