# 获取工厂信息
GET http://localhost:8080/client/factoryInfo

###

# 获取班组信息
GET http://localhost:8080/client/teamInfo

###

# 客户端登录
POST http://localhost:8080/client/login
Content-Type: application/json

{
  "teamCode": "001",
  "machineCode": "机台1"
}

###

# 获取订单列表
GET http://localhost:8080/client/orderList
Content-Type: application/json
Authorization: 98b69d392688433f90d57cd42f140e7b

{
  "page": 1,
  "pageSize": 10
}


###

# 获取当前编码规则
GET http://localhost:8080/client/currentCodeRule
Authorization: 98b69d392688433f90d57cd42f140e7b


###

# 获取订单的编码规则    
GET http://localhost:8080/client/orderCodeRule?orderId=1
Authorization: 98b69d392688433f90d57cd42f140e7b


###

# 采集上传
POST http://localhost:8080/client/collectUpload
Content-Type: application/json
Authorization: 98b69d392688433f90d57cd42f140e7b

{
  "boxQrCode": "1234567890",
  "orderId": "1",
  "collectDateTime": "2021-01-01 00:00:00",
  "codeRuleId": 4,
  "bagQrCodeList":["123","456"]

}







